import time
from selenium.webdriver.common.by import By
from WebPages.BasePage import BasePage

class JDPage(BasePage):
    JD_BTN=(By.XPATH, "/html[1]/body[1]/div[3]/div[2]/nav[1]/a[3]")
    JD_CREATE_BTN=(By.XPATH, "/html[1]/body[1]/div[2]/div[3]/div[1]/div[1]/button[2]")
    JD_AI_MODE_OFF=(By.ID, "jdModeToggle")
    JOB_TITLE=(By.ID, "job_title")
    JOB_LOCATION=(By.ID, "location")
    JOB_TYPE_DD_BTN=(By.ID, "job_type")
    JOB_TYPE_SEL=(By.XPATH, "(//option[@value='Temporary'])[1]")
    WORK_MODE_DD_BTN=(By.ID, "work_mode")
    WORK_MODE_SEL=(By.XPATH, "(//option[@value='Remote'])[1]")
    EXPERIENCE=(By.ID, "experience_required")
    VACANCIES=(By.ID, "no_vacancies")
    SKILLS=(By.ID, "skills")
    JOB_SUMMARY=(By.ID, "job_summary")
    JOB_RESPONSIBILITIES=(By.ID, "responsibilities")
    JD_SAVE_BTN=(By.ID, "submitBtnText")
    JOB_TITLE_REQ_MSG=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[2]/form[1]/div[1]/div[1]/div[1]")
    JOB_LOCATION_REQ_MSG=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[2]/form[1]/div[1]/div[2]/div[1]")
    JOB_TYPE_REQ_MSG=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[2]/form[1]/div[1]/div[3]/div[1]")
    WORK_MODE_REQ_MSG=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[2]/form[1]/div[1]/div[4]/div[1]")
    EXPERIENCE_REQ_MSG=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[2]/form[1]/div[1]/div[5]/div[1]")
    VACANCIES_REQ_MSG=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[2]/form[1]/div[1]/div[6]/div[1]")
    SKILLS_REQ_MSG=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[2]/form[1]/div[1]/div[7]/div[1]")
    JOB_SUMMARY_REQ_MSG=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[2]/form[1]/div[1]/div[8]/div[1]/div[1]")
    JOB_RESPONSIBILITIES_REQ_MSG=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[2]/form[1]/div[1]/div[8]/div[2]/div[1]")
    SEL_JD_CB=(By.XPATH, "(//input[@type='checkbox'])[5]")
    JD_DEL_BTN=(By.XPATH, "/html[1]/body[1]/div[2]/div[3]/div[1]/div[1]/button[1]")
    CON_JD_DEL=(By.ID, "confirmDeleteJDBtn")
    JD_3_DOTS=(By.XPATH, "/html[1]/body[1]/div[2]/div[3]/div[2]/div[2]/div[1]/table[1]/tbody[1]/tr[5]/td[6]/div[1]")
    VIEW_JD=(By.XPATH, "/html[1]/body[1]/div[2]/div[3]/div[2]/div[2]/div[1]/table[1]/tbody[1]/tr[5]/td[6]/div[1]/ul[1]/li[1]/button[1]")
    EDIT_JD_BTN=(By.XPATH, "/html[1]/body[1]/div[2]/div[6]/div[1]/div[1]/div[2]/div[2]/button[1]")
    WORK_MODE_EDIT=(By.ID, "edit-work-mode")
    SEL_WORK_MODE_EDIT=(By.XPATH, "(//option[@value='Hybrid'])[2]")
    SAVE_EDIT_JD=(By.ID, "saveEditBtn")
    PUBLISH_BTN=(By.XPATH, "/html[1]/body[1]/div[2]/div[3]/div[2]/div[2]/div[1]/table[1]/tbody[1]/tr[5]/td[6]/div[1]/ul[1]/li[2]/button[1]")
    DELETE_PUBLISH_BTN=(By.XPATH, "/html[1]/body[1]/div[2]/div[3]/div[2]/div[2]/div[1]/table[1]/tbody[1]/tr[5]/td[6]/div[1]/ul[1]/li[4]/button[1]")
    JD_CLOSE_BTN=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[1]/button[1]")

    def __init__(self,driver):
        super().__init__(driver)

    def create_JD_Manually(self, job_name, location, experience, vacancies, skills, summary, responsibilities):
        self.do_click(self.JD_BTN)
        time.sleep(1)
        self.do_click(self.JD_CREATE_BTN)
        time.sleep(1)
        self.do_click(self.JD_AI_MODE_OFF)
        time.sleep(1)
        self.do_send_keys(self.JOB_TITLE, job_name)
        time.sleep(1)
        self.do_send_keys(self.JOB_LOCATION, location)
        time.sleep(1)
        self.do_click(self.JOB_TYPE_DD_BTN)
        time.sleep(1)
        self.do_click(self.JOB_TYPE_SEL)
        time.sleep(1)
        self.do_click(self.WORK_MODE_DD_BTN)
        time.sleep(1)
        self.do_click(self.WORK_MODE_SEL)
        time.sleep(1)
        self.do_send_keys(self.EXPERIENCE, experience)
        time.sleep(1)
        self.do_send_keys(self.VACANCIES, vacancies)
        time.sleep(1)
        self.do_send_keys(self.SKILLS, skills)
        time.sleep(1)
        self.do_send_keys(self.JOB_SUMMARY, summary)
        time.sleep(1)
        self.do_send_keys(self.JOB_RESPONSIBILITIES, responsibilities)
        time.sleep(1)
        self.do_click(self.JD_SAVE_BTN)

    def default_JD_Creation(self):
        self.do_click(self.JD_CREATE_BTN)
        time.sleep(1)
        self.do_click(self.JD_AI_MODE_OFF)
        time.sleep(1)
        self.do_click(self.JD_SAVE_BTN)
        time.sleep(1)
        text_job=self.get_element_text(self.JOB_TITLE_REQ_MSG)
        print(text_job)
        text_location=self.get_element_text(self.JOB_LOCATION_REQ_MSG)
        print(text_location)
        text_type=self.get_element_text(self.JOB_TYPE_REQ_MSG)
        print(text_type)
        text_mode=self.get_element_text(self.WORK_MODE_REQ_MSG)
        print(text_mode)
        text_experience=self.get_element_text(self.EXPERIENCE_REQ_MSG)
        print(text_experience)
        text_vacancies=self.get_element_text(self.VACANCIES_REQ_MSG)
        print(text_vacancies)
        text_skills=self.get_element_text(self.SKILLS_REQ_MSG)
        print(text_skills)
        text_summary=self.get_element_text(self.JOB_SUMMARY_REQ_MSG)
        print(text_summary)
        text_resposibilities= self.get_element_text(self.JOB_RESPONSIBILITIES_REQ_MSG)
        print(text_resposibilities)

    def leave_one_field_create_jd(self,job_name, location, experience, vacancies, skills, summary):
        self.do_send_keys(self.JOB_TITLE, job_name)
        time.sleep(1)
        self.do_send_keys(self.JOB_LOCATION, location)
        time.sleep(1)
        self.do_click(self.JOB_TYPE_DD_BTN)
        time.sleep(1)
        self.do_click(self.JOB_TYPE_SEL)
        time.sleep(1)
        self.do_click(self.WORK_MODE_DD_BTN)
        time.sleep(1)
        self.do_click(self.WORK_MODE_SEL)
        time.sleep(1)
        self.do_send_keys(self.EXPERIENCE, experience)
        time.sleep(1)
        self.do_send_keys(self.VACANCIES, vacancies)
        time.sleep(1)
        self.do_send_keys(self.SKILLS, skills)
        time.sleep(1)
        self.do_send_keys(self.JOB_SUMMARY, summary)
        time.sleep(1)
        self.do_click(self.JD_SAVE_BTN)
        time.sleep(1)
        text_resposibilities = self.get_element_text(self.JOB_RESPONSIBILITIES_REQ_MSG)
        print(text_resposibilities)
        self.do_click(self.JD_CLOSE_BTN)
        time.sleep(1)

    def edit_jd(self):
        self.do_click(self.JD_3_DOTS)
        time.sleep(1)
        self.do_click(self.VIEW_JD)
        time.sleep(1)
        self.do_click(self.EDIT_JD_BTN)
        time.sleep(1)
        self.do_click(self.WORK_MODE_EDIT)
        time.sleep(2)
        self.do_click(self.SEL_WORK_MODE_EDIT)
        time.sleep(2)
        self.do_click(self.SAVE_EDIT_JD)
        time.sleep(1)

    def publish_delete_publish_jd(self):
        self.do_click(self.JD_3_DOTS)
        time.sleep(1)
        self.do_click(self.PUBLISH_BTN)
        time.sleep(2)
        self.do_click(self.JD_3_DOTS)
        time.sleep(1)
        self.do_click(self.DELETE_PUBLISH_BTN)
        time.sleep(1)

    def delete_jd(self):
        self.do_click(self.SEL_JD_CB)
        time.sleep(1)
        self.do_click(self.JD_DEL_BTN)
        time.sleep(1)
        self.do_click(self.CON_JD_DEL)
        time.sleep(1)


