import time

from select import select
from selenium.webdriver.common.by import By
from WebPages.BasePage import BasePage
from WebPages.HomePage import HomePage

class SA_UserCreatePage(BasePage):
    CREATE_USER_BTN=(By.XPATH, "//button[normalize-space()='Create User']")
    MANAGE_USERS_BTN=(By.CSS_SELECTOR, "body > div:nth-child(3) > div:nth-child(2) > nav:nth-child(1) > a:nth-child(2)")
    NAME_FIELD=(By.ID, "first-name1")
    EMP_FIELD=(By.CSS_SELECTOR, "input[placeholder='Enter Employee ID'][name='emp_id']")
    PHN_NO_FIELD=(By.ID, "phone-number1")
    EMAIL_FIELD=(By.ID, "email_id")
    CREATE_USER_PWD=(By.ID, "addUserPassword")
    SELECT_ROLE_DROP_DOWN=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[2]/form[1]/div[1]/div[5]/div[1]/div[1]")
    SELECT_HR=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[2]/form[1]/div[1]/div[5]/div[1]/ul[1]/li[2]")
    SELECT_TL=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[2]/form[1]/div[1]/div[5]/div[1]/ul[1]/li[3]")
    SELECT_SA=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[2]/form[1]/div[1]/div[5]/div[1]/ul[1]/li[1]")
    CREATE_USER=(By.XPATH, "//button[normalize-space()='Create']")
    INACTIVE_STATE=(By.NAME, "is_active")
    SHOW_PASSWORD=(By.ID, "toggle_add_password")
    GENERATE_PASSWORD=(By.XPATH, "button[onclick='generatePassword(event)']")
    NAME_REQUIRED_MSG=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[2]/form[1]/div[1]/div[1]/small[1]")
    EMP_ID_REQUIRED_MSG=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[2]/form[1]/div[1]/div[2]/small[1]")
    PHN_NO_REQUIRED_MSG=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[2]/form[1]/div[1]/div[3]/small[1]")
    EMAIL_REQUIRED_MSG=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[2]/form[1]/div[1]/div[4]/small[2]")
    PASSWORD_REQUIRED_MSG=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[2]/form[1]/div[1]/div[6]/div[1]/div[1]/small[1]")
    ROLE_MISSING_FIELD_MSG=(By.CSS_SELECTOR, "div[class='col-md-6 form-group'] div[class='text-danger small']")
    CLICK_3_DOTS=(By.XPATH, "/html[1]/body[1]/div[2]/div[3]/form[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[1]/td[8]/div[1]/button[1]/*[name()='svg'][1]")
    CLICK_EDIT=(By.XPATH, "/html[1]/body[1]/div[2]/div[3]/form[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[1]/td[8]/div[1]/ul[1]/li[1]/a[1]")
    EDIT_PHN_FIELD=(By.ID, "phone-number")
    UPDATE=(By.XPATH, "/html[1]/body[1]/div[2]/div[3]/div[2]/div[1]/div[1]/div[2]/form[1]/div[1]/div[9]/button[1]")
    CHECK_BOX=(By.NAME, "emp_ids")
    USER_DELETE_BTN=(By.ID, "deleteSelectedBtn")
    USER_CON_DELETE_BTN=(By.ID, "confirmDeleteUserBtn")
    CLOSE_PAGE=(By.XPATH, "/html[1]/body[1]/div[2]/div[4]/div[1]/div[1]/div[1]/a[1]")
    ROLES_BTN=(By.ID, "selected-role")
    ROLES_OPTIONS=(By.CLASS_NAME, "dropdown-option")
    SETTINGS_BTN=(By.XPATH, "//span[normalize-space()='Settings']")
    CMS_FORM_BTN=(By.XPATH, "//a[normalize-space()='CMS Form']")
    CREATE_CMS_BTN=(By.ID, "createFieldBtn")
    FIELD_NAME=(By.ID, "fieldLabel")
    INPUT_TYPE_DD=(By.ID, "inputType")
    INPUT_TYPE=(By.XPATH, "//option[@value='star_rating']")
    VISIBILITY_HR=(By.ID, "visHR")
    OPERATION_HR=(By.ID, "opHR")
    VISIBILITY_TL=(By.ID, "visTL")
    OPERATION_TL=(By.ID, "opTL")
    SAVE_FIELD=(By.ID, "saveFieldBtn")
    PREVIEW_BTN=(By.ID, "previewBtn")
    CLOSE_PREVIEW_PAGE=(By.XPATH, "/html[1]/body[1]/div[5]/div[1]/div[1]/div[1]/button[1]")
    CHECK_BOX_BTN=(By.XPATH, "(//input[@class='form-check-input select-checkbox'])[1]")
    DELETE_BTN=(By.ID, "deleteFieldBtn")
    CON_DELETE=(By.ID, "confirmDeleteBtn")

    def __init__(self,driver):
        super().__init__(driver)

    def create_user_hr(self, user_name, emp_id, phn_no, email, password):
        self.do_click(self.MANAGE_USERS_BTN)
        time.sleep(1)
        self.do_click(self.CREATE_USER_BTN)
        time.sleep(1)
        self.do_send_keys(self.NAME_FIELD, user_name)
        time.sleep(1)
        self.do_send_keys(self.EMP_FIELD, emp_id)
        time.sleep(1)
        self.do_send_keys(self.PHN_NO_FIELD, phn_no)
        time.sleep(1)
        self.do_send_keys(self.EMAIL_FIELD, email)
        time.sleep(1)
        self.do_click(self.SELECT_ROLE_DROP_DOWN)
        time.sleep(1)
        self.do_click(self.SELECT_HR)
        time.sleep(1)
        self.do_send_keys(self.CREATE_USER_PWD, password)
        time.sleep(1)
        self.do_click(self.CREATE_USER)
        time.sleep(4)

    def create_blank_user(self):
        self.do_click(self.CREATE_USER_BTN)
        time.sleep(1)
        self.do_click(self.CREATE_USER)
        time.sleep(1)
        text_name=self.get_element_text(self.NAME_REQUIRED_MSG)
        print(text_name)
        text_emp_id=self.get_element_text(self.EMP_ID_REQUIRED_MSG)
        print(text_emp_id)
        text_phn_no=self.get_element_text(self.PHN_NO_REQUIRED_MSG)
        print(text_phn_no)
        text_email=self.get_element_text(self.EMAIL_REQUIRED_MSG)
        print(text_email)
        text_password=self.get_element_text(self.PASSWORD_REQUIRED_MSG)
        print(text_password)
        time.sleep(2)

    def leave_one_field_and_create(self, user_name, emp_id, phn_no, email, password):
        self.do_send_keys(self.NAME_FIELD, user_name)
        time.sleep(1)
        self.do_send_keys(self.EMP_FIELD, emp_id)
        time.sleep(1)
        self.do_send_keys(self.PHN_NO_FIELD, phn_no)
        time.sleep(1)
        self.do_send_keys(self.EMAIL_FIELD, email)
        time.sleep(1)
        self.do_send_keys(self.CREATE_USER_PWD, password)
        time.sleep(1)
        self.do_click(self.CREATE_USER)
        time.sleep(1)
        text=self.get_element_text(self.ROLE_MISSING_FIELD_MSG)
        print(text)
        self.do_click(self.CLOSE_PAGE)
        time.sleep(2)

    def Edit_User(self, phnNo):
        self.do_click(self.CLICK_3_DOTS)
        time.sleep(1)
        self.do_click(self.CLICK_EDIT)
        time.sleep(1)
        phone=self.driver.find_element(*self.EDIT_PHN_FIELD)
        phone.clear()
        self.do_send_keys(self.EDIT_PHN_FIELD, phnNo)
        time.sleep(1)
        self.do_click(self.UPDATE)
        time.sleep(2)

    def Delete_User(self):
        self.do_click(self.CHECK_BOX)
        time.sleep(1)
        self.do_click(self.USER_DELETE_BTN)
        time.sleep(1)
        self.do_click(self.USER_CON_DELETE_BTN)
        time.sleep(1)

    def Filter_Section(self):
        self.select_dropdown_value(self.ROLES_BTN, self.ROLES_OPTIONS, "HR")

    def CMS_Section(self, field_name):
        self.do_click(self.SETTINGS_BTN)
        time.sleep(1)
        self.do_click(self.CMS_FORM_BTN)
        time.sleep(1)
        self.do_click(self.CREATE_CMS_BTN)
        time.sleep(1)
        self.do_send_keys(self.FIELD_NAME, field_name)
        time.sleep(1)
        self.do_click(self.INPUT_TYPE_DD)
        time.sleep(1)
        self.do_click(self.INPUT_TYPE)
        time.sleep(1)
        self.do_click(self.VISIBILITY_HR)
        time.sleep(1)
        self.do_click(self.OPERATION_HR)
        time.sleep(1)
        self.do_click(self.VISIBILITY_TL)
        time.sleep(1)
        self.do_click(self.OPERATION_TL)
        time.sleep(1)
        self.do_click(self.SAVE_FIELD)
        time.sleep(2)
        self.do_click(self.PREVIEW_BTN)
        time.sleep(1)
        self.do_click(self.CLOSE_PREVIEW_PAGE)
        time.sleep(2)
        self.do_click(self.CHECK_BOX_BTN)
        time.sleep(1)
        self.do_click(self.DELETE_BTN)
        time.sleep(1)
        self.do_click(self.CON_DELETE)
        time.sleep(1)
